// import { Sequelize } from 'sequelize-typescript';
// import Roles from '@/models/master/roles.model';
// import Privileges from '@/models/master/privileges.model';
// import Processes from '@/models/master/process.model';
// import AgentProcess from '@/models/master/agentProcess.model';
// import RolesPrivileges from '@/models/master/rolesPrivileges.model';
// import Breaks from '@/models/master/breaks.model';
// import Dispositions from '@/models/master/disposition.model';
// import Clients from '@/models/master/clients.model';
// import Merchants from '@/models/master/merchants.model';
// import Users from '@/models/master/user.model';
// import CustomerDisposition from '@/models/master/customerDisposition.model';
// import Dialers from '@/models/master/dialers.model';
// import DialerUsers from '@/models/master/dialerUsers.model';
// import Customers from '@/models/master/customers.model';
// import DataFileModel from '@/models/master/dataFile.model';
// import SMS from '@/models/master/sms.model';
// import CallSummaries from '@/models/master/callSummaries.model';
// import AgentStatus from '@/models/master/agentStatuses.model';
// import SubDisposition from '@/models/master/subDisposition.model';
// import Payments from '@/models/master/payments.model';
// import SystemLogs from '@/models/master/systemLog.model';

// import Whatsapp from '@/models/master/whatsapp.model';
// import IVR from '@/models/master/ivr.model';
// import CurrentCallInitiate from '@/models/master/currentCall.model';
// import Template from '@/models/master/template.model';
// import TemplateParameter from '@/models/master/templateParameter.model';
// import MessageFile from '@/models/master/messageFile.model';
// import CronList from '@/models/master/cronList.model';
// import UserManager from '@/models/master/userManager.model';
// import DatabaseModule from '@/models/master/modules.model';
// import { Pages } from '@/models/master/pages.model';
// import Permission from '@/models/master/permissions.model';
// import RolePermission from '@/models/master/rolePermissions.model';
// import ACLModules from '@/models/master/modules.model';
// import Settlement from '@/models/master/settlements.model';
// import SettlementStatus from '@/models/master/settlements_status.model';
// import LoginDetails from '@/models/master/loginDetails.model';
// import ProductTypes from '../models/master/productTypes.model';
// import Products from '@/models/master/products.model';
// import NoticeCategory from '@/models/master/noticeCategory.model';
// import Emails from '@/models/master/email.model';
// import NoticeSteps from '@/models/master/noticeSteps.model';
// import Notices from '@/models/master/notice.model';
// import ProcessConfig from '@/models/master/processConfig.model';
// import P1Model from '@/models/master/p1Data.model';
// import AgentStats from '@/models/master/agentStats.model';
// import SupervisorStats from '@/models/master/supervisorStats.model';
// import LoginStats from '@/models/master/loginStats.model';

// export interface BaseSequelize {
//   sequelize: Sequelize;
//   Sequelize: typeof Sequelize;
// }
// export interface MasterDB extends BaseSequelize {
//   users: typeof Users;
//   dialerUsers: typeof DialerUsers;
//   roles: typeof Roles;
//   breaks: typeof Breaks;
//   clients: typeof Clients;
//   merchants: typeof Merchants;
//   dispositions: typeof Dispositions;
//   subDispositions: typeof SubDisposition;
//   privileges: typeof Privileges;
//   processes: typeof Processes;
//   processConfig: typeof ProcessConfig;
//   agentProcess: typeof AgentProcess;
//   rolesPrivileges: typeof RolesPrivileges;
//   dialers: typeof Dialers;
//   customers: typeof Customers;
//   payments: typeof Payments;
//   customerdisposition: typeof CustomerDisposition;

//   // customerloandetails: typeof CustomerLoanDetails;
//   datafiles: typeof DataFileModel;
//   sms: typeof SMS;
//   ivr: typeof IVR;
//   whatsapp: typeof Whatsapp;
//   callsummaries: typeof CallSummaries;
//   agentstatuses: typeof AgentStatus;
//   currentCallInitiate: typeof CurrentCallInitiate;
//   systemlogs: typeof SystemLogs;
//   template: typeof Template;
//   templateParameter: typeof TemplateParameter;
//   messageFile: typeof MessageFile;
//   cronList: typeof CronList;
//   userManager: typeof UserManager;
//   modules: typeof DatabaseModule;
//   aclModules: typeof ACLModules;
//   permissions: typeof Permission;
//   pages: typeof Pages;
//   rolePermissions: typeof RolePermission;
//   settlement: typeof Settlement;
//   settlementStatus: typeof SettlementStatus;
//   loginDetails: typeof LoginDetails;
//   productTypes: typeof ProductTypes;
//   products: typeof Products;
//   noticeCategory: typeof NoticeCategory;
//   emails: typeof Emails;
//   noticeSteps: typeof NoticeSteps;
//   notices: typeof Notices;
//   P1Model: typeof P1Model;
//   agentStats: typeof AgentStats;
//   loginStats: typeof LoginStats;
//   supervisorStats: typeof SupervisorStats;
// }
